/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ramdheproject;
import javax.swing.*;
import javax.swing.table.AbstractTableModel.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Datamhs extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;

    /**
     * Creates new form Datamhs
     */
    public Datamhs() {
        initComponents();
        setTitle("Form Input Data Mahasiswa");
        kosongkan();
    }
        
private void kosongkan(){
     name.setText("");
     id.setText("");
     kel.setSelectedItem("");
     jrs.setSelectedItem("");
     cls.setText("");
     sms.setText("");
     lokasi.setText("");
     
     religi.setSelectedItem("");
     alt.setText("");
     name.requestFocus();
     
    }
private DefaultTableModel model;
private String SQL;

private void tampilkan_data(){
    DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("NIM");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jurusan/Prodi");
        model.addColumn("Kelas");
        model.addColumn("Semester");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Agama");
        model.addColumn("Alamat");
        try{
            int no = 1;
            String sql = "SELECT * FROM datamhs";
            java.sql.Connection conn= (Connection)konfig.configDB();
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1), res.getString(2), res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});
            }
            
            table.setModel(model);
            
        }catch (Exception e){
            System.out.println("Error!" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alt = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        cls = new javax.swing.JTextField();
        sms = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        lokasi = new javax.swing.JTextField();
        religi = new javax.swing.JComboBox();
        kel = new javax.swing.JComboBox();
        jrs = new javax.swing.JComboBox();
        ext = new javax.swing.JButton();
        edt = new javax.swing.JButton();
        smpn = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        mmenu = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        dlt = new javax.swing.JButton();
        bgdatamhs = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ramdheproject/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 0, 850, 180);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Mahasiswa");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 200, 160, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 530, 80, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kembali");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 700, 160, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIM :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 290, 100, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 320, 150, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jurusan/Prodi : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 350, 130, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kelas :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 380, 80, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 410, 120, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tempat Lahir :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 440, 130, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Agama : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(110, 500, 80, 20);
        jPanel1.add(alt);
        alt.setBounds(180, 530, 460, 20);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(270, 260, 250, 20);
        jPanel1.add(cls);
        cls.setBounds(190, 380, 170, 20);
        jPanel1.add(sms);
        sms.setBounds(200, 410, 160, 20);
        jPanel1.add(id);
        id.setBounds(270, 290, 260, 20);
        jPanel1.add(lokasi);
        lokasi.setBounds(230, 440, 190, 20);

        religi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Animisme", "Ateis", "Budha", "Dinamisme", "Hindu", "Islam", "Kristen Katholik", "Kristen Protestan", "Konghucu", " " }));
        jPanel1.add(religi);
        religi.setBounds(180, 500, 108, 20);

        kel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "Pria", "Wanita" }));
        kel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelActionPerformed(evt);
            }
        });
        jPanel1.add(kel);
        kel.setBounds(240, 320, 59, 20);

        jrs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "Akuntansi", "Ekonomi", "Ilmu Komunikasi", "Kedokteran", "Manajemen", "Teknik Industri", "Teknik Informatika", "Teknik Mesin", " ", " " }));
        jPanel1.add(jrs);
        jrs.setBounds(240, 350, 113, 20);

        ext.setBackground(new java.awt.Color(255, 0, 0));
        ext.setForeground(new java.awt.Color(255, 255, 255));
        ext.setText("Keluar");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        jPanel1.add(ext);
        ext.setBounds(10, 60, 80, 30);

        edt.setText("Edit");
        edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtActionPerformed(evt);
            }
        });
        jPanel1.add(edt);
        edt.setBounds(550, 240, 51, 23);

        smpn.setText("Simpan");
        smpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpnActionPerformed(evt);
            }
        });
        jPanel1.add(smpn);
        smpn.setBounds(690, 530, 73, 23);

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari);
        cari.setBounds(780, 530, 51, 23);

        mmenu.setBackground(new java.awt.Color(0, 51, 204));
        mmenu.setForeground(new java.awt.Color(255, 255, 255));
        mmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ramdheproject/back.png"))); // NOI18N
        mmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmenuActionPerformed(evt);
            }
        });
        jPanel1.add(mmenu);
        mmenu.setBounds(60, 610, 80, 90);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Mahasiswa :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(110, 260, 160, 20);

        table.setBackground(new java.awt.Color(0, 204, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 610, 1360, 980);

        dlt.setText("Hapus");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        jPanel1.add(dlt);
        dlt.setBounds(620, 240, 90, 23);

        bgdatamhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ramdheproject/WhatsApp Image 2021-07-11 at 20.29.07.jpeg"))); // NOI18N
        bgdatamhs.setText("jLabel2");
        jPanel1.add(bgdatamhs);
        bgdatamhs.setBounds(0, -60, 1590, 1310);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 1210, 1550, 130);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 1390, 1550, 140);

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 1630, 1550, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1858, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_extActionPerformed

    private void mmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmenuActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_mmenuActionPerformed

    private void datelhrPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datelhrPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_datelhrPropertyChange

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        try{
            res=stat.executeQuery("select * from datamhs"+ "nama='"+ name.getText()+"'");
            while(res.next())
            {name.setText(res.getString("nama"));
     id.setText(res.getString("nim"));
     kel.setSelectedItem(res.getString("gender"));
     jrs.setSelectedItem(res.getString("prodi"));
     cls.setText(res.getString("kelas"));
     sms.setText(res.getString("semester"));
     lokasi.setText(res.getString("tempathr"));
     
     religi.setSelectedItem(res.getString("agama"));
     alt.setText(res.getString("alamat"));
     }
   }catch (Exception e){
       JOptionPane.showMessageDialog(rootPane, e);
   }
    }//GEN-LAST:event_nameActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null, "Hapus?","Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try{
                String sql="delete from datamhs where nama='"+name.getText()+"'";
                PreparedStatement st=con.prepareStatement(sql);
                st.executeUpdate();
                kosongkan();
                JOptionPane.showMessageDialog(null, "Data Terhapus");
                new Datamhs().setVisible(true);
                dispose();
            }catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Data Tidak Dapat Dihapus");
            }
        }
    }//GEN-LAST:event_dltActionPerformed

    private void smpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpnActionPerformed
        // TODO add your handling code here:
        try{
            stat.executeUpdate("insert into datamhs values("+"'"+name.getText()+"',"+"'"+id.getText()+"',"+"'"+kel.getSelectedItem()+"',"+"'"+jrs.getSelectedItem()+"',"+"'"+cls.getText()+"',"+"'"+sms.getText()+"',"+"'"+lokasi.getText()+"',"+"'"+"',"+"'"+religi.getSelectedItem()+"',"+"'"+alt.getText()+"')");
            kosongkan();
            JOptionPane.showMessageDialog(null, "Data Telah Tersimpan");
            new Datamhs().setVisible(true);
            dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan!! Data Tidak Tersimpan"+e);
        }
    }//GEN-LAST:event_smpnActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        try{
            res=stat.executeQuery("select * from datamhs"+ "nama='"+ name.getText()+"'");
            while(res.next())
            {name.setText(res.getString("nama"));
     id.setText(res.getString("nim"));
     kel.setSelectedItem(res.getString("gender"));
     jrs.setSelectedItem(res.getString("prodi"));
     cls.setText(res.getString("kelas"));
     sms.setText(res.getString("semester"));
     lokasi.setText(res.getString("tempathr"));
     
     religi.setSelectedItem(res.getString("agama"));
     alt.setText(res.getString("alamat"));
     }
   }catch (Exception e){
       JOptionPane.showMessageDialog(rootPane, e);
   }
    }//GEN-LAST:event_cariActionPerformed

    @SuppressWarnings("empty-statement")
    private void edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE datamhs SET nama='"+name.getText()+"',nim='"+id.getText()+"',gender='"+kel.getSelectedItem()+"',prodi='"+jrs.getSelectedItem()+"',kelas='"+cls.getText()+"',semester='"+sms.getText()+"',tempathr='"+lokasi.getText()+"',agama='"+religi.getSelectedItem()+"',alamat='"+alt.getText()+"'WHERE nama = '"+name.getText()+"'";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Telah Berhasil Dilakukan");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Di Edit"+e.getMessage());
        }
        tampilkan_data();
        kosongkan();
    }//GEN-LAST:event_edtActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.rowAtPoint(evt.getPoint());
        String nama = model.getValueAt(index, 0).toString();
        String nim = model.getValueAt(index, 1).toString();
        String gender = model.getValueAt(index, 2).toString();
        String prodi = model.getValueAt(index, 3).toString();
        String kelas = model.getValueAt(index, 4).toString();
        String semester = model.getValueAt(index, 5).toString();
        String tempathr = model.getValueAt(index, 6).toString();
        String tanggallhr = model.getValueAt(index, 7).toString();
        String agama = model.getValueAt(index, 8).toString();
        String alamat = model.getValueAt(index, 9).toString();
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datamhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datamhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datamhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datamhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datamhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alt;
    private javax.swing.JLabel bgdatamhs;
    private javax.swing.JButton cari;
    private javax.swing.JTextField cls;
    private javax.swing.JButton dlt;
    private javax.swing.JButton edt;
    private javax.swing.JButton ext;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jrs;
    private javax.swing.JComboBox kel;
    private javax.swing.JTextField lokasi;
    private javax.swing.JButton mmenu;
    public javax.swing.JTextField name;
    private javax.swing.JComboBox religi;
    private javax.swing.JButton smpn;
    private javax.swing.JTextField sms;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    
    };
