/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ramdheproject;

/**
 *
 * @author Admin
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        quit = new javax.swing.JToggleButton();
        lookmenu = new javax.swing.JToggleButton();
        input1 = new javax.swing.JToggleButton();
        labellihat = new javax.swing.JLabel();
        inputlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 51, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Main Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(700, 230, 100, 14);

        quit.setBackground(new java.awt.Color(255, 51, 51));
        quit.setForeground(new java.awt.Color(255, 255, 255));
        quit.setText("Keluar");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jPanel1.add(quit);
        quit.setBounds(390, 630, 120, 23);

        lookmenu.setBackground(new java.awt.Color(0, 153, 255));
        lookmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ramdheproject/12.png"))); // NOI18N
        lookmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookmenuActionPerformed(evt);
            }
        });
        jPanel1.add(lookmenu);
        lookmenu.setBounds(570, 280, 110, 100);

        input1.setBackground(new java.awt.Color(255, 204, 0));
        input1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ramdheproject/23.png"))); // NOI18N
        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        jPanel1.add(input1);
        input1.setBounds(810, 280, 100, 100);

        labellihat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labellihat.setForeground(new java.awt.Color(255, 255, 255));
        labellihat.setText("Tambahkan Data ");
        jPanel1.add(labellihat);
        labellihat.setBounds(810, 390, 120, 14);

        inputlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputlabel.setForeground(new java.awt.Color(255, 255, 255));
        inputlabel.setText("Logout");
        jPanel1.add(inputlabel);
        inputlabel.setBounds(590, 390, 200, 20);

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(680, 220, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ramdheproject/7p_2hzkryqe-luis-llerena.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 4600, 3181);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 4513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 3199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed
        // TODO add your handling code here:
        new Datamhs().setVisible(true);
        dispose();
    }//GEN-LAST:event_input1ActionPerformed

    private void lookmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookmenuActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_lookmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton input1;
    private javax.swing.JLabel inputlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labellihat;
    private javax.swing.JToggleButton lookmenu;
    private javax.swing.JToggleButton quit;
    // End of variables declaration//GEN-END:variables
}
